tests/test_cli: remove __main__ code.
This no longer works:

   $ python3 tests/test_cli.py
   Traceback (most recent call last):
     File ".../ult/tests/test_cli.py", line 14, in <module>
       from .tools import (
   ImportError: attempted relative import with no known parent package

References: commit 49696a6100606511781c637ea9d4b89e23530704